apiVersion: v1
kind: Service
metadata:
  name: my-cicd-app-service
spec:
  selector:
    app: my-cicd-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
